version: "3.2"



services:
  db:
    image: postgres:9.3
    environment:
      - POSTGRES_USER=eo
      - POSTGRES_DB=kn
      - POSTGRES_PASSWORD=chucha11
      - POSTGRES_HOST=db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"



  server: 
    image: falidana/myserver
    restart: always
    environment:
      - POSTGRES_USER=eo
      - POSTGRES_DB=kn
      - POSTGRES_PASSWORD=chucha11
      - POSTGRES_HOST=db
    depends_on:
      - db
    links:
      - db
    volumes: 
      - '.:/myshop/'
    ports:
      - "2225:22"
      - "80:8000"

volumes:
  postgres_data:
